// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEyocrc4JhgGOmsQh0c9v22RPlSdmbkXg',
    appId: '1:665265458229:web:63154b4ebb5ef47480f57c',
    messagingSenderId: '665265458229',
    projectId: 'soframdaneeksik',
    authDomain: 'soframdaneeksik.firebaseapp.com',
    storageBucket: 'soframdaneeksik.firebasestorage.app',
    measurementId: 'G-C02EDX4T64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD223RRBO7LR1KmhtFSEG1dX4pq0qUvwo',
    appId: '1:665265458229:android:18e6fe61dc48f88380f57c',
    messagingSenderId: '665265458229',
    projectId: 'soframdaneeksik',
    storageBucket: 'soframdaneeksik.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASQR7aQvyNV6S9CLtnK7ufdIyP4DE70JE',
    appId: '1:665265458229:ios:196ba150fccbb03380f57c',
    messagingSenderId: '665265458229',
    projectId: 'soframdaneeksik',
    storageBucket: 'soframdaneeksik.firebasestorage.app',
    iosBundleId: 'com.benyaparim.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASQR7aQvyNV6S9CLtnK7ufdIyP4DE70JE',
    appId: '1:665265458229:ios:196ba150fccbb03380f57c',
    messagingSenderId: '665265458229',
    projectId: 'soframdaneeksik',
    storageBucket: 'soframdaneeksik.firebasestorage.app',
    iosBundleId: 'com.benyaparim.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEyocrc4JhgGOmsQh0c9v22RPlSdmbkXg',
    appId: '1:665265458229:web:056373cb8174f0ff80f57c',
    messagingSenderId: '665265458229',
    projectId: 'soframdaneeksik',
    authDomain: 'soframdaneeksik.firebaseapp.com',
    storageBucket: 'soframdaneeksik.firebasestorage.app',
    measurementId: 'G-MM01NPVGGX',
  );
}
